In [214]:
import pandas as pd
import numpy as np

In [215]:
filename ="customer_churn_dataset-training-master.csv"

In [216]:
customer = pd.read_csv(filename)
customer.head(10)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0
5,8.0,51.0,Male,33.0,25.0,9.0,26.0,Premium,Annual,129.0,8.0,1.0
6,9.0,58.0,Female,49.0,12.0,3.0,16.0,Standard,Quarterly,821.0,24.0,1.0
7,10.0,55.0,Female,37.0,8.0,4.0,15.0,Premium,Annual,445.0,30.0,1.0
8,11.0,39.0,Male,12.0,5.0,7.0,4.0,Standard,Quarterly,969.0,13.0,1.0
9,12.0,64.0,Female,3.0,25.0,2.0,11.0,Standard,Quarterly,415.0,29.0,1.0

In [217]:
#Check the number of columns in the dataset

customer.shape[1]

12

In [218]:
#Check the number of rows in the dataset

customer.shape[0]

440833

In [219]:
#Print out the Columns names 
customer.columns.to_list()

['CustomerID',
 'Age',
 'Gender',
 'Tenure',
 'Usage Frequency',
 'Support Calls',
 'Payment Delay',
 'Subscription Type',
 'Contract Length',
 'Total Spend',
 'Last Interaction',
 'Churn']

In [220]:
#Print the columns and datatype 

customer.dtypes

CustomerID           float64
Age                  float64
Gender                   str
Tenure               float64
Usage Frequency      float64
Support Calls        float64
Payment Delay        float64
Subscription Type        str
Contract Length          str
Total Spend          float64
Last Interaction     float64
Churn                float64
dtype: object

In [221]:
#Identify duplkicate in the dataset

customer.duplicated().sum()  

#Zero duplicate result found

np.int64(0)

In [222]:
#Identify missing values

null = customer.isnull().sum()
null

#There is one null value across allthe columns

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [223]:
#Remove a missing or null value

customer.dropna(inplace =True)

#Reproint the total number of rows 

customer.shape[0] 
    #The total rows has drropped by 1 from 440833 to 440832 after removing a null value (missing  value)

440832

In [224]:
customer.info()

<class 'pandas.DataFrame'>
Index: 440832 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 38.7 MB

In [225]:
#Convert the CustomerID, Age, Tenure, Support Calls, Patment Delay, Usage Frequency, Last Interaction, Churn from float to interger

customer[['CustomerID','Age','Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay','Last Interaction', 'Churn']] =customer[['CustomerID','Age','Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay', 'Last Interaction', 'Churn']].astype(int)

In [226]:
customer

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2,30,Female,39,14,5,18,Standard,Annual,932.00,17,1
1,3,65,Female,49,1,10,8,Basic,Monthly,557.00,6,1
2,4,55,Female,14,4,6,18,Basic,Quarterly,185.00,3,1
3,5,58,Male,38,21,7,7,Standard,Monthly,396.00,29,1
4,6,23,Male,32,20,5,8,Basic,Monthly,617.00,20,1
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995,42,Male,54,15,1,3,Premium,Annual,716.38,8,0
440829,449996,25,Female,8,13,1,20,Premium,Annual,745.38,2,0
440830,449997,26,Male,35,27,1,5,Standard,Quarterly,977.31,9,0
440831,449998,28,Male,55,14,2,0,Standard,Quarterly,602.55,2,0
440832,449999,31,Male,48,20,1,14,Premium,Quarterly,567.77,21,0

In [227]:
#RE-print the final datatype of Customr databases after casting floats into intergers

In [228]:
#Print unique target variable 
for col in ['Churn', 'Gender', 'Subscription Type', 'Contract Length']:
    print(col, customer[col].unique())

Churn [1 0]
Gender <StringArray>
['Female', 'Male']
Length: 2, dtype: str
Subscription Type <StringArray>
['Standard', 'Basic', 'Premium']
Length: 3, dtype: str
Contract Length <StringArray>
['Annual', 'Monthly', 'Quarterly']
Length: 3, dtype: str

In [229]:
#Remove excess space and upper case the first letter of text objects

for col in ['Gender', 'Subscription Type', 'Contract Length']:
    customer[col] = customer[col].str.strip().str.title()

In [230]:
#Print eandom 10 results

customer.sample(20)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
306886,314000,37,Female,41,21,0,8,Standard,Annual,748.01,10,0
229716,235816,28,Female,10,19,2,3,Basic,Monthly,159.20,16,1
326589,333704,21,Male,41,24,2,0,Standard,Annual,669.63,18,0
381701,388816,23,Male,30,10,2,14,Basic,Quarterly,613.11,10,0
72676,74462,54,Female,24,12,10,16,Standard,Monthly,218.00,21,1
36821,37049,33,Male,38,4,3,25,Premium,Monthly,830.00,10,1
309858,316973,21,Male,14,18,1,13,Standard,Annual,957.48,16,0
402254,409369,31,Female,8,6,1,1,Basic,Quarterly,744.38,5,0
70945,72643,20,Female,7,9,0,4,Premium,Monthly,360.00,7,1
370620,377735,40,Male,31,25,2,13,Standard,Quarterly,661.38,12,0
90509,93067,44,Female,59,3,4,2,Basic,Quarterly,605.00,19,1
304959,312073,42,Male,57,7,3,9,Standard,Annual,839.38,10,0
87743,90172,22,Female,1,15,10,28,Premium,Quarterly,393.00,29,1
185888,190699,55,Female,36,1,0,28,Basic,Monthly,894.00,15,1
392123,399238,30,Female,14,21,3,1,Basic,Quarterly,963.42,2,0
124412,128411,57,Male,6,18,3,3,Premium,Monthly,894.00,11,1
149793,154604,49,Female,56,2,2,19,Standard,Annual,258.00,5,1
155094,159905,60,Male,45,2,3,26,Premium,Monthly,439.00,4,1
183180,187991,18,Male,28,29,2,23,Basic,Quarterly,672.00,12,1
200846,205719,18,Male,35,24,7,1,Standard,Annual,191.20,23,1